### ISSUE TITLE
Node.js 12 actions are deprecated, upgrade GH action to Node.js 16

### ISSUE THREAD

**Issue by britt-645** [Asana/comment-on-task-github-action#18]
![Screenshot 2023-03-15 at 11 40 53 AM](https://user-images.githubusercontent.com/116007906/225362923-e080f33e-dd50-457d-a297-88b6abf7a05d.png)

Is there a plan to update the action to run on Node 16?

[https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions)

[https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**Comment by whitershade** [comment]
@britt-645 Hi! Have you tried the [new version of the action](https://github.com/marketplace/actions/add-comment-to-asana-task) from the marketplace?

<img width="406" alt="Screenshot 2023-03-17 at 12 10 56" src="https://user-images.githubusercontent.com/14962514/225875758-ccf5b288-120a-4e32-8d5a-236beefb401b.png">

**Comment by britt-645** [comment]
Hi @whitershade! We were using `@latest`, which is what was generated by the instructions here: https://github.com/marketplace/actions/add-comment-to-asana-task#step-3-create-a-workflow-file

I'll try using `@v1.2`

**Comment by whitershade** [comment]
updated README.md
